{% set name = "neptune-aws" %}
{% set package_name = "neptune_aws" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 74f0ab3f7fa5f4bf9574ef004f72591054576e417a86a094af34691bd7ff7dae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.7
    - neptune-client >=0.15.0
    - boto3

test:
  imports:
    - neptune_aws
    - neptune_aws.impl
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Utilities for using Neptune client on AWS
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/
  dev_url: https://github.com/neptune-ai/{{ name }}

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - Raalsky
    - twolodzko
    - AleksanderWWW
